# High Resolution
# Deliberately swapped variant of monitors.conf (see swap-monitors.sh)
monitor = desc:LG Electronics LG ULTRAGEAR 312NTFA44579, 2560x1440@144, 0x0, 1    # left
monitor = desc:LG Electronics LG ULTRAGEAR 408NTYT32250, 2560x1440@144, 2560x0, 1 # right
#Fallback
; monitor = DP-2, 2560x1440@144, 0x0, 1
; monitor = DP-1, 2560x1440@144, auto, 1

#
