# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #

# *********************************************************** #
# 
# NOTE: This will be overwritten by NWG-Displays 
# once you use and click apply. 
#
# *********************************************************** #

# You can set workspace rules to achieve workspace-specific behaviors. 
# For instance, you can define a workspace where all windows are drawn without borders or gaps.

# https://wiki.hyprland.org/Configuring/Workspace-Rules/

$leftMonitor = HDMI-A-1
$rightMonitor = DP-2
